In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from sklearn.model_selection import train_test_split

import unicodedata
import re
import numpy as np
import os
import io
import time

In [2]:
# 下载文件
path_to_zip = tf.keras.utils.get_file(
    'spa-eng.zip', origin='http://storage.googleapis.com/download.tensorflow.org/data/spa-eng.zip',
    extract=True)

path_to_file = os.path.dirname(path_to_zip)+"/spa-eng/spa.txt"

2646016/2638744 [==============================] - 913s 345us/step


In [159]:
inputs = np.array(([[[1,2,3],[2,3,4]]])).astype(np.float32)

gru = tf.keras.layers.GRU(5, return_sequences=True, return_state=True)
x = gru(inputs)
x

[<tf.Tensor: shape=(1, 2, 5), dtype=float32, numpy=
 array([[[-0.47335434,  0.25466466, -0.45010966, -0.33190084,
          -0.34508836],
         [-0.70042676,  0.5640548 , -0.61880547, -0.52530444,
          -0.51686233]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=
 array([[-0.70042676,  0.5640548 , -0.61880547, -0.52530444, -0.51686233]],
       dtype=float32)>]

In [160]:
embedding = tf.keras.layers.Embedding(100, 32)

In [156]:
inputs = np.array(([[[1,2,3],[2,3,4]]])).astype(np.float32)

lstm = tf.keras.layers.LSTM(5, return_sequences=True, return_state=True)

# whole_sequence_output, final_memory_state, final_carry_state = lstm(inputs)
x = lstm(inputs)

In [157]:
x

[<tf.Tensor: shape=(1, 2, 5), dtype=float32, numpy=
 array([[[-0.05497233, -0.088308  , -0.12244754, -0.03459666,
          -0.00848369],
         [-0.03116414, -0.40509602, -0.202125  , -0.0223077 ,
           0.041026  ]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=
 array([[-0.03116414, -0.40509602, -0.202125  , -0.0223077 ,  0.041026  ]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=
 array([[-1.0147184 , -0.55159557, -0.3376758 , -0.02345872,  0.05121391]],
       dtype=float32)>]

In [67]:
inputs.shape

(1, 2, 3)